# Generated by Django 5.2.1 on 2025-05-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_medecin_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedecinSpecialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='core.medecinprofile')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecins', to='core.specialite')),
            ],
            options={
                'unique_together': {('medecin', 'specialite')},
            },
        ),
    ]
